{{- if .Values.arangodb.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: arangodb
  name: arangodb
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: arangodb
    spec:
      containers:
      - args:
        - arangod
        - --server.endpoint
        - tcp://0.0.0.0:8529
        env:
        - name: ARANGO_NO_AUTH
          value: "1"
        image: arangodb/arangodb
        name: arangodb
        ports:
        - containerPort: 8529
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/arangodb3
          name: arangodb-data
      hostname: arangodb
      restartPolicy: Always
      volumes:
      - name: arangodb-data
        persistentVolumeClaim:
          claimName: arangodb-data
  selector:
    matchLabels:
      io.kompose.service: arangodb
status: {}
{{- end -}}