{{- if .Values.fileIndex.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-web
spec:
  selector:
    io.kompose.service: mottainai
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
data:
#/etc/nginx/conf.d/default.conf
  default.conf: |
          server {
            listen       80;
            server_name  localhost;

            root   /opt/www/files/;
            index  index.html index.htm;
            autoindex on;


            error_page   500 502 503 504  /50x.html;
            location = /50x.html {
              root   /usr/share/nginx/html;
            }

          }
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nginx-web
  {{- with .Values.fileIndex.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.fileIndex.ingress.tls }}
  tls:
  {{- range .Values.fileIndex.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.fileIndex.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        - path: /
          backend:
            serviceName: nginx-web
            servicePort: 80
  {{- end }}
{{- end -}}
