apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mottainai-artifacts
  name: mottainai-artifacts
spec:
  storageClassName: {{ .Values.storageClass }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.artefactsVolumeSize }}
status: {}
