apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mottainai-namespaces
  name: mottainai-namespaces
spec:
  storageClassName: {{ .Values.storageClass }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.namespaceVolumeSize }}
status: {}
