
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mottainai-storages
  name: mottainai-storages
spec:
  storageClassName: {{ .Values.storageClass }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storagesVolumeSize }}
status: {}
