apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: 1.16.0 (0c01309)
  {{- with .Values.redis.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}

  creationTimestamp: null
  labels:
    io.kompose.service: redis
  name: redis
spec:
  {{ if .Values.service.redisType  }}
  type: {{ .Values.service.redisType }}
  {{ end }}
  {{- if .Values.service.redisExternalIPs  -}}
  externalIPs:
  {{- range .Values.service.redisExternalIPs }}
  - {{ . | quote }}
  {{- end }}
  {{- end }}
  ports:
  - name: "{{ .Values.service.redisPort }}"
    port: {{ .Values.service.redisPort }}
    targetPort: {{ .Values.service.redisPort }}
  selector:
    io.kompose.service: redis
status:
  loadBalancer: {}
