{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mottainai.serviceAccountName" . }}
  labels:
{{ include "mottainai.labels" . | nindent 4 }}
{{- end -}}
